[package]
description = "Advent of Code 2021"
authors = ["Seth Junot <xsetech@gmail.com>"]
name = "aoc-2021-sjunot"
version = "0.2.0"
edition = "2021"

[profile.release]
debug = true
lto = true
panic = "abort"
opt-level = "s"
