[package]
description = "Advent of Code - Day 2 Soln"
authors = ["Seth Junot <xsetech@gmail.com>"]
name = "day02"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
lto = true
panic = "abort"
opt-level = "s"
